# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
    ];

  services.flatpak.enable = true;

  environment.systemPackages = with pkgs; [
    wget
    zoxide
    nix-zsh-completions
    git
    gh
    vscode
    ncspot
    flameshot
    vimix-cursor-theme
    kitty
    yazi
  ];

  # Steam
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true; # Open ports in the firewall for Steam Remote Play
    dedicatedServer.openFirewall = true; # Open ports in the firewall for Source Dedicated Server
    localNetworkGameTransfers.openFirewall = true; # Open ports in the firewall for Steam Local Network Game Transfers
  };

  # Kitty config symlink
  environment.sessionVariables = {
    TERMINAL = "kitty";
  };
  home-manager.users.flynn = { config, pkgs, ... }: {
    xdg.configFile = {
      "kitty" = {
            source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nix/config/kitty";
            recursive = true;
      };
    };
  };

  # Set yazi as default file explorer
  xdg.mime.defaultApplications = {
    "inode/directory" = "yazi.desktop";
  };
}
