# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  environment.systemPackages = with pkgs; [
    rustup
    gcc
  ];

  home-manager.users.flynn = { pkgs, ... }: {
    home.sessionPath = [ "$HOME/.cargo/bin" ];
  };
}
