# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
home-manager.users.flynn = {
	programs.neovim = {
	  enable = true;
	  defaultEditor = true;
	  extraConfig = ''
	    set number relativenumber
	    set clipboard+=unnamedplus
	  '';
	};	
};
}
