# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
    #important imports
      ./home.nix #for configuring home-manager
      ./user.nix #for configuring user specific config
      ./untracked.nix #for things specific to hardware/usecase
      ./applications.nix #for low config applications like discord
      ./dev.nix #for apps/config around development
    #modules
    #things that need enough configuration to demand their own file
      ./zsh.nix
      ./nvim.nix
    ];

}
